################################ USERS ################################
GET http://localhost:3000/users/
Content-Type: application/json

### CREATE USER
POST http://localhost:3000/users/
Content-Type: application/json

{
    "fullname": "Devri",
    "email": "dv@gmail.com",
    "password": "123",
    "phone": "0822",
    "gender": "Male",
    "address": "Indonesia",
    "nickname": "Devri",
    "birthday": "03/01/2001"
}

### GET USER BY ID
GET http://localhost:3000/users/26
Content-Type: application/json

### UPDATE USER
POST http://localhost:3000/users/26
Content-Type: application/json

{
    "fullname": "Devri 22",
    "email": "dv@gmail.com",
    "password": "123",
    "phone": "0822",
    "gender": "Male",
    "address": "Indonesia",
    "nickname": "Devri",
    "birthday": "03/01/2001"
}

### DELETE USER BY ID
DELETE http://localhost:3000/users/26
Content-Type: application/json


################################ VEHICLE ################################
GET http://localhost:3000/vehicle/
Content-Type: application/json

### QUERY
GET http://localhost:3000/vehicle/all?sort=desc
Content-Type: application/json

### SEARCH
GET http://localhost:3000/vehicle/all?search=m
Content-Type: application/json

### CREATE VEHICLE
POST http://localhost:3000/vehicle/
Content-Type: application/json

{
    "name": "Sepeda",
    "city": "city",
    "available": true,
    "prepayment": false,
    "capacity": 2,
    "type": "Bike",
    "reservation": "08-05-2022",
    "price": "Rp100.000",
    "likes": 299,
    "quantity": 5
}

### GET VEHICLE BY ID
GET http://localhost:3000/vehicle/17
Content-Type: application/json

### UPDATE VEHICLE
POST http://localhost:3000/vehicle/17
Content-Type: application/json

{
    "name": "Sepeda2",
    "city": "city",
    "available": true,
    "prepayment": false,
    "capacity": 2,
    "type": "Bike",
    "reservation": "08-05-2022",
    "price": "Rp100.000",
    "likes": 299,
    "quantity": 5
}

### DELETE VEHICLE
DELETE http://localhost:3000/vehicle/17
Content-Type: application/json

### POPULAR VEHICLE
GET http://localhost:3000/vehicle/popular
Content-Type: application/json

################################ HISTORY ################################
GET http://localhost:3000/history/
Content-Type: application/json

### CREATE
POST http://localhost:3000/history/
Content-Type: application/json

{
    "name": "Sepeda",
    "Duration": "2 Day",
    "prepayment": "Rp200.000",
    "returned": false,
    "user_id": 26
}

### QUERY
GET http://localhost:3000/history/all?sort=asc
Content-Type: application/json

### SEARCH
GET http://localhost:3000/history/all?search=m
Content-Type: application/json

### GET HISTORY ID
GET http://localhost:3000/history/21
Content-Type: application/json

### DELETE HISTORY ID
DELETE http://localhost:3000/history/21
Content-Type: application/json