################################ USERS ################################
GET http://localhost:3000/users/
Content-Type: application/json

### REGISTER USER
POST http://localhost:3000/users/
Content-Type: application/json

{
    "fullname": "devri",
    "email": "dev@gmail.com",
    "password": "123456",
    "phone": "082255554551",
    "gender": "Male",
    "address": "Indonesia",
    "nickname": "Devri",
    "birthday": "03/01/2001"
}

### LOGIN USER
POST http://localhost:3000/auth/
Content-Type: application/json

{
    "email": "dev@gmail.com",
    "password": "123456"
}

### GET USER BY ID
GET http://localhost:3000/users/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NTA3MTIwNX0.aMzHFMRLjiWcB-gH5zo_NCuXFIh9SMWEr1cg_aVhYng

### UPDATE USER
PUT http://localhost:3000/users/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NTA2ODc0MH0.9Etc0uPQoInz14lhgCroSbJAhY4bm3WpEaKZs9rmjPI

{
    "fullname": "admin",
    "email": "admin@admin.com",
    "password": "123452",
    "phone": "082255554554",
    "gender": "Male",
    "address": "Indonesia",
    "nickname": "Devri",
    "birthday": "03/01/2001"
}

### DELETE USER BY ID
DELETE http://localhost:3000/users/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NTA3MTIwNX0.aMzHFMRLjiWcB-gH5zo_NCuXFIh9SMWEr1cg_aVhYng


################################ VEHICLE ################################
GET http://localhost:3000/vehicle/
Content-Type: application/json

### CREATE VEHICLE
POST http://localhost:3000/vehicle/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NTA2ODc0MH0.9Etc0uPQoInz14lhgCroSbJAhY4bm3WpEaKZs9rmjPI

{
    "name": "Mobil",
    "city": "Indonesia",
    "available": true,
    "prepayment": false,
    "capacity": 2,
    "type": "Bike",
    "reservation": "20-05-2022",
    "price": "Rp1.000.000",
    "likes": 5,
    "quantity": 2
}

### GET VEHICLE BY ID
GET http://localhost:3000/vehicle/
Content-Type: application/json

### UPDATE VEHICLE
PUT http://localhost:3000/vehicle/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NTA2ODc0MH0.9Etc0uPQoInz14lhgCroSbJAhY4bm3WpEaKZs9rmjPI

{
    "name": "Mobil",
    "city": "Indonesia",
    "available": true,
    "prepayment": false,
    "capacity": 2,
    "type": "Bike",
    "reservation": "20-05-2022",
    "price": "Rp1.000.000",
    "likes": 5,
    "quantity": 2
}

### DELETE VEHICLE
DELETE http://localhost:3000/vehicle/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NTA2ODc0MH0.9Etc0uPQoInz14lhgCroSbJAhY4bm3WpEaKZs9rmjPI

### POPULAR VEHICLE
GET http://localhost:3000/vehicle/popular
Content-Type: application/json

### SORT
GET http://localhost:3000/vehicle/all?sort=asc
Content-Type: application/json

### SEARCH
GET http://localhost:3000/vehicle/all?search=mo
Content-Type: application/json

################################ HISTORY ################################
GET http://localhost:3000/history/
Content-Type: application/json

### CREATE
POST http://localhost:3000/history/
Content-Type: application/json

{
    "name": "",
    "Duration": "2 Day",
    "prepayment": "Rp200.000",
    "returned": false,
    "user_id": 13
}

### QUERY
GET http://localhost:3000/history/all?sort=desc
Content-Type: application/json

### SEARCH
GET http://localhost:3000/history/all?search=m
Content-Type: application/json

### GET HISTORY ID
GET http://localhost:3000/history/9
Content-Type: application/json

### DELETE HISTORY ID
DELETE http://localhost:3000/history/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NTA3MjI1Nn0.epCnRbwBIV1ElSgsShqetgLTN4GKTA114XKWKlmEuyg