################################ USERS ################################
GET http://localhost:3000/users/
Content-Type: application/json

### REGISTER USER
POST http://localhost:3000/users/
Content-Type: application/json

{
    "fullname": "devri",
    "email": "dev@gmail.com",
    "password": "123456",
    "phone": "082255554551",
    "gender": "Male",
    "address": "Indonesia",
    "nickname": "Devri",
    "birthday": "03/01/2001"
}

### LOGIN USER
POST http://localhost:3000/auth/
Content-Type: application/json

{
    "email": "dev@gmail.com",
    "password": "123"
}

### GET USER BY ID
GET http://localhost:3000/users/42
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNjU0OTQ4Njg2fQ.eIjE9BR7aF3jqZAidu2xWU4g4Ad6J-sMqE08JVi_jNs

### UPDATE USER
PUT http://localhost:3000/users/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NTAyNTg2OX0.4I-vg4TpdreIK5CeEoQC4eyuhWNQyCLeW8Nfxg5FpP4

{
    "fullname": "admin",
    "email": "admin@admin.com",
    "password": "123452",
    "phone": "082255554554",
    "gender": "Male",
    "address": "Indonesia",
    "nickname": "Devri",
    "birthday": "03/01/2001"
}

### DELETE USER BY ID
DELETE http://localhost:3000/users/46
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NDk0OTA0Mn0.k9Xe428bA-GVEmV-UwW-HIhiBf4HfJQvYvKhIcpm3mI


################################ VEHICLE ################################
GET http://localhost:3000/vehicle/
Content-Type: application/json

### CREATE VEHICLE
POST http://localhost:3000/vehicle/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NDk0OTA0Mn0.k9Xe428bA-GVEmV-UwW-HIhiBf4HfJQvYvKhIcpm3mI

{
    "name": "Sepeda",
    "city": "Indonesia",
    "available": true,
    "prepayment": false,
    "capacity": 2,
    "type": "Bike",
    "reservation": "20-05-2022",
    "price": "Rp1.000.000",
    "likes": 5,
    "quantity": 2
}

### GET VEHICLE BY ID
GET http://localhost:3000/vehicle/2
Content-Type: application/json

### UPDATE VEHICLE
PUT http://localhost:3000/vehicle/25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NDk0OTA0Mn0.k9Xe428bA-GVEmV-UwW-HIhiBf4HfJQvYvKhIcpm3mI

{
    "name": "Sepeda update",
    "city": "city",
    "available": true,
    "prepayment": false,
    "capacity": 2,
    "type": "Bike",
    "reservation": "20-05-2022",
    "price": "Rp1.000.000",
    "likes": 5,
    "quantity": 2
}

### DELETE VEHICLE
DELETE http://localhost:3000/vehicle/25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImV4cCI6MTY1NDk0OTA0Mn0.k9Xe428bA-GVEmV-UwW-HIhiBf4HfJQvYvKhIcpm3mI

### POPULAR VEHICLE
GET http://localhost:3000/vehicle/popular
Content-Type: application/json

### QUERY
GET http://localhost:3000/vehicle/all?search=mo&sort=asc
Content-Type: application/json

### SEARCH
GET http://localhost:3000/vehicle/all?search=mo
Content-Type: application/json

################################ HISTORY ################################
GET http://localhost:3000/history/
Content-Type: application/json

### CREATE
POST http://localhost:3000/history/
Content-Type: application/json

{
    "name": "Sepeda",
    "Duration": "2 Day",
    "prepayment": "Rp200.000",
    "returned": false,
    "user_id": 26
}

### QUERY
GET http://localhost:3000/history/all?sort=asc
Content-Type: application/json

### SEARCH
GET http://localhost:3000/history/all?search=m
Content-Type: application/json

### GET HISTORY ID
GET http://localhost:3000/history/21
Content-Type: application/json

### DELETE HISTORY ID
DELETE http://localhost:3000/history/21
Content-Type: application/json